version: "3"
services:
    blog:
        build: .
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pakt-blog.rule=Host(`blog.pakt.dev`)"
            - "traefik.http.services.pakt-blog.loadbalancer.server.port=5000"
            - "traefik.http.routers.pakt-blog.service=pakt-blog"
            - "traefik.http.routers.pakt-blog.tls=true"
            - "traefik.http.routers.pakt-blog.tls.certresolver=lets-encrypt"
