version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "pakt-blog"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`blog.pakt.dev`)"
      - "traefik.http.routers.whoami.entrypoints=web"