version: "3"
services:
    blog:
        build: ./
        restart: unless-stopped
        networks:
            - web
            - default

        environment:
                - FLASK_APP=app/main.py
                - FLASK_DEBUG=1
                - 'RUN=flask run --host=0.0.0.0 --port=80'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pakt-blog.rule=Host(`blog.pakt.dev`)"
            - "traefik.http.routers.pakt-blog.tls=true"
            - "traefik.http.routers.pakt-blog.tls.certresolver=lets-encrypt"

networks:
    web:
        external: true